server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: bankuser
    password: bankpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        transaction:
          coordinator_class: jdbc
        enable_lazy_load_no_trans: false
        format_sql: true
        use_sql_comments: true
        query:
          startup_check: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
    default-schema: public

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret-key: YourSecretKey123
  secret: yourverylongandsecurejwtsecretkeyatleast256bitslonghere
  expiration: 3600000

domain:
  front: http://front:3000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.internal.NamedQueryRepository: WARN
    org.hibernate.engine.query.spi.NamedQueryDefinition: WARN
    org.hibernate.jpa.internal: WARN
    org.hibernate.resource.transaction: WARN
    liquibase: INFO